http:
  host: "![1sC63GLMGyMnMmEyMkGpkw==]"
  port: "![e5baCWGL32I=]"
  path: "![7ppzdkTPclc=]"

api:
  host: "![QN7VxIcJZBeYq6qDtmV9q1yM68rCgumy]"
  Path: "![Ll9bSMgmCckmLJYY6mN18jPpwAif0Ys6B8A5eYgXdlE=]"
  access_key: "![2dahqqZzauJQE0XNff+ICU/+k+gSFwfTVXAWdntqej/mnaU/3b7iCQ==]"
