#%RAML 1.0 Trait
headers:
  ClientID:
    description: The registered Clinet ID
    type: string
    required: true
    example: 3e9oty9kiretfd3ewqasder34xzed52s
  ClientSecret:
    description: The registered Clinet Secret
    type: string
    required: true
    example: 3e9oty9kiretfd3ewqasder34xzed52q